### ISSUE TITLE
[CONSOLE] Add Matomo Analytics for Generic Visitor Data

### ISSUE THREAD

**Issue by vmichalik** [superfluid-finance/superfluid-console#118] opened 2022-09-27 09:56 UTC
- Tracking code to insert on each page can be found here
https://superfluidfinance.matomo.cloud/index.php?module=CoreAdminHome&action=trackingCodeGenerator&idSite=2&period=day&date=yesterday&updated=false
- Contact Vijay if Matomo login is needed

**Comment by tokdaniel** [comment] 2022-09-29 08:59
I think this is a duplicate of https://app.zenhub.com/workspaces/user-products-team-61fba509b1fbfb00106daf63/issues/superfluid-finance/superfluid-console/47

**Closed** 2022-10-12 11:59 UTC
Labels: Type: Enhancement, Size: S, Project: CONSOLE
